### ISSUE TITLE
Can't download anything.

### ISSUE THREAD

**Issue by Noboty** [quangaming2929/UniversalAnimeDownloader#4]
Maybe I am missing something, but I cannot read (what I think is) Vietnamese, so I cannot figure out what I am missing. Basically, I click download and nothing happens. Tried several shows. Nothing.

**Comment by HoangTheBoss** [comment]
The application is not finished and never built so please wait for further updates.

**Comment by HoangTheBoss** [comment]
Also, the application needs dependencies which aren't public at this time.

**Comment by tachibanayui** [comment]
I am sorry because you have experience this issue. I already made a video show that the download process usually takes up to 2 minutes after you click download all button depend on how many episodes are there in the series. We are constantly try no speed up this process.

Side note: we will release a new version by the end of this month so I hope you will enjoy the new feature we have include in. Feel free to comment if you need more help

Sorry for my bad English

**Comment by tachibanayui** [comment]
@HoangTheBoss I think he is asking about the v0.8.0 version and I think you are talking about the new version 0.9 because the installer in version 0.8.0 already include all necessary dependencies to function.
